### PR TITLE
Added 14 new prompts

### PR DESCRIPTION
**Pull request by lucaskenji**
Related to issue #2 
Modified prompts.ts in order to add 14 more conversation prompts

### CODE REVIEW

**Comment by lucaskenji** [comment]
Hello, sorry if it's a stupid question but I don't understand what you mean by sorting the new ones into the list.
(Also, how about letting the user suggest some prompts to add?)

**Comment by tylermercer** [comment]
So right now, the ones higher in the list don't require a lot of personal
vulnerability to discuss. For example, "What would the perfect day look
like for you?" is something you could talk about with basically anyone,
whereas "The death of which of your family members would impact you the
most" is a much deeper question and requires more vulnerability.

I'd like to maintain that ordering as new prompts are added. That was what
I meant by sorting them in.

I'll make a commit to this branch that shows what I mean.

**Comment by tylermercer** [comment]
> Hello, sorry if it's a stupid question but I don't understand what you mean by sorting the new ones into the list.
> (Also, how about letting the user suggest some prompts to add?)

Re: user-suggested prompts: I just added this as issue #6.

**Comment by lucaskenji** [comment]
> So right now, the ones higher in the list don't require a lot of personal vulnerability to discuss. For example, "What would the perfect day look like for you?" is something you could talk about with basically anyone, whereas "The death of which of your family members would impact you the most" is a much deeper question and requires more vulnerability. I'd like to maintain that ordering as new prompts are added. That was what I meant by sorting them in. I'll make a commit to this branch that shows what I mean.
I guess I skipped the text that explained that on the app, now I understand. Should I make another commit or does your commit solve that problem?

**Comment by tylermercer** [comment]
> 
> 
> > So right now, the ones higher in the list don't require a lot of personal vulnerability to discuss. For example, "What would the perfect day look like for you?" is something you could talk about with basically anyone, whereas "The death of which of your family members would impact you the most" is a much deeper question and requires more vulnerability. I'd like to maintain that ordering as new prompts are added. That was what I meant by sorting them in. I'll make a commit to this branch that shows what I mean.
> 
> I guess I skipped the text that explained that on the app, now I understand. Should I make another commit or does your commit solve that problem?

That solves it! I'll go ahead and merge. Thanks for contributing!

**Pull request merged**
